name: 'slack-copy'
description: 'Copying files via slack channel out of a github action runner'
inputs:
  what-to-copy:  # path of the file to copy 
    description: 'Path of the file to copy'
    required: true
    default: './*'
runs:
  using: "composite"
  steps:
    - run: echo Gonna copy this file ...  ${{ inputs.what-to-copy }}.
      shell: bash
    - run: ${{ github.action_path }}/slack-copy.sh
      shell: bash
